-- local status, lualine = pcall(require, "lualine")
-- if (not status) then return end

-- local git_blame = require('gitblame')

-- require('lualine').setup {
--   options = {
--     icons_enabled = true,
--     theme = 'seoul256',
--     component_separators = { left = '|', right = '|' },
--     section_separators = { left = '', right = '' },
--     disabled_filetypes = {
--       statusline = {},
--       winbar = {},
--     },
--     ignore_focus = {},
--     always_divide_middle = true,
--     globalstatus = false,
--     refresh = {
--       statusline = 1000,
--       tabline = 1000,
--       winbar = 1000,
--     }
--   },
--   sections = {
--     lualine_a = {},
--     lualine_b = { 'mode' },
--     lualine_c = {
--       {
--         'filename',
--         path = 1
--       }
--     },
--     lualine_x = {
--       { git_blame.get_current_blame_text, cond = git_blame.is_blame_text_available }
--     },
--     lualine_y = {},
--     lualine_z = {}
--   },
--   inactive_sections = {
--     lualine_a = {},
--     lualine_b = {},
--     lualine_c = { 'filename' },
--     lualine_x = { 'location' },
--     lualine_y = {},
--     lualine_z = {}
--   },
--   tabline = {},
--   winbar = {},
--   inactive_winbar = {},
--   extensions = {}
-- }
