version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgvol:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:7
    ports:
      - 6379:6379
    restart: always
  mongodb:
    image: mongo:4.0.14
    volumes:
      - /data/db
    command: --smallfiles
    ports:
      - 27017:27017
    restart: always

volumes:
  pgvol:
