# Config relating to the Lazygit UI
disableStartupPopups: true

gui:
  authorColors:
    'kanatsanan6': blue
    'Kanatsanan Janpakdee': blue
    '*': magenta
  showBottomLine: false
  showCommandLog: false
  showListFooter: false
  showRandomTip: false
  showPanelJumps: false
  border: single
  theme:
    activeBorderColor:
      - white
      - bold
git:
  paging:
    pager: diff-so-fancy
