#!/bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

if git rev-parse --git-dir > /dev/null 2>&1; then
    existing_pr=$(gh pr list --head "$current_branch" --limit 1)

    if [[ -n "$existing_pr" ]]; then
        pr_number=$(echo "$existing_pr" | awk '{print $1}')
        gh pr view "$pr_number" --web
    else
        gh pr create --web --base main --head "$current_branch"
    fi
fi
